In [1]:
import numpy as np

In [ ]:
# travis oliphant  numpy - written in c

# Numpy Arrays


list vs arrays

- list - can store different datatypes 
- array- stores only single type of data 

In [5]:
# array creation
np.array({1,2,3,4,5})


array({1, 2, 3, 4, 5}, dtype=object)

In [16]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [15]:
a=[1,2,3,4,"hello"]
# here all data types will become string as U32
arr=np.array(a)
arr

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [17]:
l=[[1,2,3],[4,5,6],[7,8,9]]
arrd=np.array(l)
arrd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

the 2d 3d 4d etc are knon as tensors

In [19]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((6,6))  #hori=row ,vrticle =columns

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
# havng linear space 

arr=np.linspace(1,2,4)  # (from,to,numbers to be formed between from anf to)
arr

array([1.        , 1.33333333, 1.66666667, 2.        ])

random number generation  (np sobat random pn install hoto so to acess an random in np we will use 'np.random.random_operarion )

In [29]:
np.random.rand(5)

array([0.38061491, 0.49087594, 0.90727893, 0.4854384 , 0.88978207])

In [30]:
np.random.randn(10)  # concept of standardization values lies between 3 and -3 thus use 'random.randn'

array([ 0.51217318, -1.09967981, -0.12653669,  0.28241253,  0.36497522,
       -1.84204134, -1.51995629,  0.63904352,  0.29936587,  0.31123516])

In [34]:
np.random.randint(1,30,10)  #( from , till , how many)

array([26, 29, 25, 14, 17, 25, 16,  6, 14, 29])

attributes in np


In [36]:
l=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(l)
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.shape

(3, 3)

In [39]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

In [42]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [44]:
arr.sum()

np.int64(45)

In [45]:
# colum wise axis =0
# colum wise axis =1

np.sum(arr,axis=0)

array([12, 15, 18])

In [46]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [48]:
arr.std()  # standardization

np.float64(2.581988897471611)

In [50]:
# finding index of largest and smallest index 

arr.argmax(),arr.argmin()

(np.int64(8), np.int64(0))

reshaping and resizing 


In [52]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [54]:
arr.reshape(6,5) # (rows, columns)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Indexing and Slicing

In [97]:
arr=np.arange(11,21)

In [98]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [99]:
arr[6]  #indexing

np.int64(17)

In [100]:
arr[1:5]   #slicing an window from given_start : end_given index

array([12, 13, 14, 15])

In [101]:
arr[5:]

array([16, 17, 18, 19, 20])

In [102]:
arr[:8]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [103]:
arr[::4]

array([11, 15, 19])

In [104]:
arr2=np.arange(1,31).reshape(6,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [105]:
sli=arr2[3:,3:]
sli

array([[19, 20],
       [24, 25],
       [29, 30]])

In [106]:
arr2[::2,1::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

boolean indexing



In [107]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [108]:
bool_index=arr%2==0

In [109]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [110]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Numpy Operations 

arithmetic operations

In [112]:
a1=np.array([1,2,3,4,5,6,7])
a2=np.array([1,2,3,4,5,6,7])

a1+a2   #here size must be same 

array([ 2,  4,  6,  8, 10, 12, 14])

broadcasting


In [2]:
l=[10,20,30,40,50]
arr=np.array(l)

In [7]:
arr+10 # broadcasting basically means fireclty doing an operation that operation with every element in an array

array([20, 30, 40, 50, 60])

In [10]:
arr2=np.arange(1,31).reshape(6,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

deep and shallow copy

In [12]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
sclice=a[:5]


In [ ]:
sclice=sclice*10
sclice

# this is the eample of shallow copy 

array([10, 20, 30, 40, 50])

In [21]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

in slicing the sliced array bascally is alloted an another location 

but when an arr is copied then that whole array is location is allocated to the same location wehe the another array is thus when we can anything from the orignal array then the another array is also affected

In [24]:
# example
b=a
print(b)

b[0:2]=90

print(f"a->> {a}")
print(f"b->> {b}")


[90 90  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
a->> [90 90  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
b->> [90 90  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


matrix operation

In [ ]:
mat1=np.array([[1,2],
               [4,5]])
mat2=np.array([[1,2],
               [4,5]])

mat1*mat2

array([[ 1,  4],
       [16, 25]])

In [ ]:
mat1 @ mat2   # its the dot product

array([[ 9, 12],
       [24, 33]])

In [36]:
np.dot(mat1,mat2)

array([[ 9, 12],
       [24, 33]])

In [ ]:
mat1.T # rowto colum ->transpose

array([[1, 4],
       [2, 5]])

advance array manupilation

1. array stacking

- here in stacking only vectors can be stacked not matrices

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])

np.vstack((a,b)) #verticle stacking

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
np.hstack((a,b))   #horiznatal  stacking


array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [43]:
np.column_stack((a,b))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

2. spliting an array


In [45]:
arr=np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(arr,2)  # horizantal split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(arr,2) # vertaicxle split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [57]:
np.vsplit(arr,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

# Exercise

In [61]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
rows_sum=np.sum(s,axis=1)
cols_sum=np.sum(s,axis=0)


In [102]:
# mat_3x3=s[0:3,0:3]
# mat_3x3.sum()
k=0
for i in range(0,9,3):
    # i=3
    for j in range(0,9,3):
        mat_3x3=s[i:i+3,j:j+3]
        if(mat_3x3.sum()!=45):
            print("not an valid sudoku")
        


In [ ]:


# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix

In [ ]:
#Find the average age of students.

In [ ]:
#Extract Math marks of all students.

In [ ]:
#Find the highest Science mark.

In [ ]:
#Get details of the student who scored more than 90 in Math.

In [ ]:
#Increase Math marks of all students by 5.

In [ ]:
#Find how many students are younger than 19.

In [ ]:

#Calculate the average marks in each subject (column-wise mean)

In [ ]:
#Get data of students who scored at least 80 in both subjects.

In [ ]:
#Replace all Science marks < 75 with 0.